//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employment_History
    {
        public int EmploymentID { get; set; }
        public int PersonID { get; set; }
        public int CompanyID { get; set; }
        public string WorkingField { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string JobExp { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
