//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_V2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Talent
    {
        [DisplayName("Talent ID")]
        public int TalentID { get; set; }
        [DisplayName("Person ID")]
        public int PersonID { get; set; }
        
        [Required]
        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [Required]
        [DisplayName("First Name")]
        public string FirstName { get; set; }
        public Nullable<int> Age { get; set; }
        [DisplayName("Living Area")]
        public string LivingArea { get; set; }
        [DisplayName("Cell Phone")]
        public string CellPhone { get; set; }
        [DisplayName("Direct Phone")]
        public string DirectPhone { get; set; }
        public string Major { get; set; }
        [DisplayName("Highest Degree")]
        public string HighestDegree { get; set; }
        [DisplayName("Gradute School")]
        public string GraduteSchool { get; set; }
        public string Citizen { get; set; }
        [DisplayName("Submission Date")]
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        [Required]
        public string Source { get; set; }
        public string LinkedIn { get; set; }
        [DisplayName("Resume Location")]
        public string ResumeLocation { get; set; }
        [DisplayName("Key Word")]
        public string KeyWord { get; set; }
    
        public virtual User User { get; set; }
    }
}
